//
// Created by nauq302 on 29/09/2020.
//

#ifndef NAUQ_GAME_ENGINE_MOUSEBUTTONCODES_HPP
#define NAUQ_GAME_ENGINE_MOUSEBUTTONCODES_HPP

#define NAUQ_MOUSE_BUTTON_1         0
#define NAUQ_MOUSE_BUTTON_2         1
#define NAUQ_MOUSE_BUTTON_3         2
#define NAUQ_MOUSE_BUTTON_4         3
#define NAUQ_MOUSE_BUTTON_5         4
#define NAUQ_MOUSE_BUTTON_6         5
#define NAUQ_MOUSE_BUTTON_7         6
#define NAUQ_MOUSE_BUTTON_8         7
#define NAUQ_MOUSE_BUTTON_LAST      NAUQ_MOUSE_BUTTON_8
#define NAUQ_MOUSE_BUTTON_LEFT      NAUQ_MOUSE_BUTTON_1
#define NAUQ_MOUSE_BUTTON_RIGHT     NAUQ_MOUSE_BUTTON_2
#define NAUQ_MOUSE_BUTTON_MIDDLE    NAUQ_MOUSE_BUTTON_3

#endif //NAUQ_GAME_ENGINE_MOUSEBUTTONCODES_HPP
